global using AppEngine.EFCore.DependencyInjection;
global using AppEngine.Logging;
global using AppEngine.Routing;
global using AppEngine.Tools;
global using AppEngine.Tools.DependencyInjection;
global using AppEngine.Tools.Enums;
global using AppEngine.Tools.Extensions;
global using AppEngine.Tools.OperationResults.AspNetCore.Http;
global using AppEngine.Tools.Settings;
global using AppEngine.Tools.TimeZoneService;
global using AppEngine.Tools.TimeZoneService.Interfaces;
global using AppEngine.Validations.Validation;
global using AppEngine.Versioning.Options;
global using Categorie.BusinessLayer;
global using Categorie.BusinessLayer.Services;
global using Categorie.BusinessLayer.Services.Interfaces;
global using Categorie.BusinessLayer.Validations;
global using Categorie.DataAccessLayer;
global using Categorie.DataAccessLayer.Entities;
global using EntityFramework.Exceptions.SqlServer;
global using FluentValidation;
global using Microsoft.AspNetCore.HttpOverrides;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.Net.Http.Headers;
global using Microsoft.OpenApi;
global using Scalar.AspNetCore;
global using Serilog;
global using Serilog.Core;
global using AEToolDJ = AppEngine.Tools.DependencyInjection.ServiceCollectionExtensions;
global using EFCoreDJ = AppEngine.EFCore.DependencyInjection.ServiceCollectionExtensions;
global using ErrorResponseFormat = AppEngine.Validations.Validation.ErrorResponseFormat;
global using ErrorResposeFormatOR = AppEngine.Tools.OperationResults.AspNetCore.Http.ErrorResponseFormat;